name: Deploy to Amazon ECS

on:
  push:
    branches: [ "test" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    environment: test

    steps:
    - name: Pull & Build
      uses: appleboy/ssh-action@master
      with:
        host: ${{ vars.SSH_HOST }}
        username: ${{ vars.SSH_USER }}
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/checkout-widget-api/
          git checkout test
          git pull
          yarn
          yarn build

    - name: DB Migration
      uses: appleboy/ssh-action@master
      with:
        host: ${{ vars.SSH_HOST }}
        username: ${{ vars.SSH_USER }}
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/checkout-widget-api
          yarn sequelize db:migrate
          yarn sequelize db:seed:all

    - name: Reload
      uses: appleboy/ssh-action@master
      with:
        host: ${{ vars.SSH_HOST }}
        username: ${{ vars.SSH_USER }}
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        script: |
          pm2 reload 0
